sudo: false
branches:
  only:
  - master
language: node_js
node_js:
- '8'
install:
- npm install
cache: npm
before_script:
  - npm run lint
script:
  - npm run bower
  - npm run dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: dist
  email: patrick@deadlypenguin.com
  name: Travis-CI
  fqdn: engravinator.com
  on:
    branch: master
env:
  global:
  - secure: cnP5zWk8gvkyt35S9JP8S/5ovjP9P5FIig5uQ7eLyJCDj7ndwH1OSNIjBgtubg/vFPaYP4FG55hqou2iNfQPNSfeiOzG5h/yyxemIkyF/Qgp901mS+KqGsEAjAYI/7rgX5PG4bwp9luTMPSh1PgGTKPAxLIT/pzJeRz/qFGLJQ8o6MIFNzSKogsjraqbIzmvF+qXOmWR7ZCwR5LE4rV5EE6DEl7x45XATKd7lhfcPKFRbUpV1ffxKtq6U8BY96lQ9sMsi2ldsG6rI3XQb1KWpd6a31GFuQA1dGie31oxi0yZpKu2nqjkmZn7g4G5e8E7aDaaAOtXgRoZDNXbsELZDF/qhWtq2ZYe1/S9l6B0N5dGhJrtoH7AyHR34d8kvM8lmw9TsO/wmpdb6GrJ7pA4X+LAubSVrxadGYvuC65Wi2BhgkeMSLeCW8YZm4pl/4F10NjSmN4iCgICCF4ShK7Ravs9iPTYPoy/W93TFSRwP8UPAfbAoa1sd+97XB+MTCM2menj9/V4gxymIkMVQwwduND606FhFsWLm+Ku9pCAS9bkxxl+Zwph/KmLTzZFnTkl0msK79RHCBblPzEmDpV2rS5ewHp3IzD5eiTOkffkxQPuYoVtb9x+8321E3rAx6zPVknI8QjurkMjbSA9TnrPyzJ2G6e/lRIMNAkre6MfvqE=
  - secure: ryJCCJ5h9sM3SRDMJHWMP50TFsTtH/uFHAHTHHRDdKclFS8iWaIzAOYENmMBzXixm06jMynizWyVGk1xCURAANhbujKWCYLsnAlI1pL0vJv9EJtCCHIMvob8wHXbuHXwjoE6SItCtMGl7vIRv/AT2badNx2JlrkRg1uxa4b/7mkZEEQfFidX9ZIL3VBZpihHUnmTY6ZS5QEXwSG2xN9KDbqmto9sticiqGlTuVR2h2jLOePNWblcr3moaVJIHQMzNcWw5fe8xJ7grJwfsB6OkhVcyytFMsBHEqqnWmTYdKuVreLxiOcQyJFyaQ7eHfjw8+W1Wbp05q+gKFcY8i/82tkirfHZxOpBeW1e8LkfeyeNDGoMU8QrfEfwNLCY5ZEZFUsiSFjwgFpqTUA2wI5a8XYda3tnmlBsfCc5c4so4CfYw+bsT5yqdib9liG4eVeeXZhYkKc5Ub+WIiaE/qQrar1K0jDTurTIxhMWfOKRmqBMCbRa6hAKLiQDHr7siZ2RItpLZBgvG5FswWVtXhuTWH2gChOCDr51gqeea+fWJFeKxrzd4QfCroBqUdqetHW6Ff0rf5OlW9Dq40+cLPQCpkBHjW/bKunQ/uxKX5T49n5XOedpgXprNKNFEDvYryspOUxT7dWfeYX69B6JnmWNswKtYvbn8OfY1QL7pNRZ8iY=
notifications:
  email:
    recipients:
      - patrick@deadlypenguin.com
    on_success: always
    on_failure: always