name: Broken Link Checker

on:
  schedule:
    - cron: '30 9 * * 1'
  push:
    branches:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: link checker
      run: |
        npm install broken-link-checker
        ./node_modules/bin/blc https://engravinator.com -ro
      env:
        CI: true